- name: MONITORING | Install apache
  yum:
    name: httpd
    state: present
  tags:
    - ansibullbot_monitoring

- name: MONITORING | Copy monitoring web page
  template:
    src: ansibot_status.cgi
    dest: /var/www/cgi-bin/
    owner: apache
    group: apache
    mode: 0755
  tags:
    - ansibullbot_monitoring

- name: MONITORING | Start and enable httpd
  service:
    name: httpd
    state: started
  tags:
    - ansibullbot_monitoring
